// Mock data for dashboard preview — swap out when API is live

export const MOCK_LEADS = [
  {
    id: 1,
    company_name: 'Apex Logistics',
    email: 'cto@apexlogistics.io',
    vip_score: 91,
    vip_tier: 'VIP',
    created_at: '2026-03-25T08:14:00Z',
    score_factors: { revenue: 30, intent: 25, fit: 20, engagement: 16 },
    rationale_object: { summary: 'High-intent SaaS logistics firm, recently hired 3 SDRs' },
    trigger_events: ['Hired VP of Sales', 'Raised Series B'],
    personalization_snippet: 'Congrats on the Series B — scaling outbound is the next unlock.',
    score_rationale: 'Strong hiring signals + product-market fit overlap',
  },
  {
    id: 2,
    company_name: 'NovaSpark AI',
    email: 'founders@novaspark.ai',
    vip_score: 84,
    vip_tier: 'VIP',
    created_at: '2026-03-25T09:02:00Z',
    score_factors: { revenue: 28, intent: 22, fit: 18, engagement: 16 },
    rationale_object: { summary: 'Seed-stage AI startup with active outbound infrastructure' },
    trigger_events: ['New product launch', 'Job post: growth lead'],
    personalization_snippet: 'Saw the product launch — your ICP looks identical to what we automate for.',
    score_rationale: 'Active hiring in growth + recent product momentum',
  },
  {
    id: 3,
    company_name: 'Meridian Health',
    email: 'operations@meridianhealth.com',
    vip_score: 73,
    vip_tier: 'High',
    created_at: '2026-03-24T15:45:00Z',
    score_factors: { revenue: 25, intent: 18, fit: 17, engagement: 13 },
    rationale_object: { summary: 'Mid-market health-tech, currently using manual outreach' },
    trigger_events: ['LinkedIn ad spend increase'],
    personalization_snippet: 'Noticed you\'re running ads — we can automate the follow-up layer.',
    score_rationale: 'Moderate fit, no automation tooling detected',
  },
  {
    id: 4,
    company_name: 'Brightfield Studio',
    email: 'hello@brightfieldstudio.co',
    vip_score: 61,
    vip_tier: 'Medium',
    created_at: '2026-03-24T11:20:00Z',
    score_factors: { revenue: 18, intent: 14, fit: 16, engagement: 13 },
    rationale_object: { summary: 'Creative agency exploring sales tooling for the first time' },
    trigger_events: ['Viewed pricing page x3'],
    personalization_snippet: null,
    score_rationale: 'Decent engagement signals, early-stage interest',
  },
  {
    id: 5,
    company_name: 'Cornerstone Dev',
    email: 'team@cornerstonedev.io',
    vip_score: 47,
    vip_tier: 'Medium',
    created_at: '2026-03-23T14:30:00Z',
    score_factors: { revenue: 14, intent: 12, fit: 11, engagement: 10 },
    rationale_object: { summary: 'Small dev shop, unclear budget signal' },
    trigger_events: [],
    personalization_snippet: null,
    score_rationale: 'Low revenue match, watchlist only',
  },
  {
    id: 6,
    company_name: 'Vantage Capital',
    email: 'info@vantagecap.com',
    vip_score: 38,
    vip_tier: 'Low',
    created_at: '2026-03-22T09:00:00Z',
    score_factors: { revenue: 10, intent: 9, fit: 10, engagement: 9 },
    rationale_object: { summary: 'Finance firm, not primary ICP but has referred clients' },
    trigger_events: [],
    personalization_snippet: null,
    score_rationale: 'Low fit score, minimal intent markers',
  },
];

export const MOCK_SEQUENCES = [
  {
    id: 101,
    company_name: 'Apex Logistics',
    email: 'cto@apexlogistics.io',
    vip_score: 91,
    vip_tier: 'VIP',
    step: 2,
    status: 'active',
    created_at: '2026-03-24T10:00:00Z',
    next_send_at: '2026-03-27T10:00:00Z',
  },
  {
    id: 102,
    company_name: 'NovaSpark AI',
    email: 'founders@novaspark.ai',
    vip_score: 84,
    vip_tier: 'VIP',
    step: 1,
    status: 'replied',
    created_at: '2026-03-25T09:10:00Z',
    next_send_at: null,
  },
  {
    id: 103,
    company_name: 'Meridian Health',
    email: 'operations@meridianhealth.com',
    vip_score: 73,
    vip_tier: 'High',
    step: 3,
    status: 'active',
    created_at: '2026-03-22T11:00:00Z',
    next_send_at: '2026-03-26T14:00:00Z',
  },
  {
    id: 104,
    company_name: 'Brightfield Studio',
    email: 'hello@brightfieldstudio.co',
    vip_score: 61,
    vip_tier: 'Medium',
    step: 1,
    status: 'pending',
    created_at: '2026-03-25T08:00:00Z',
    next_send_at: '2026-03-28T09:00:00Z',
  },
  {
    id: 105,
    company_name: 'Cornerstone Dev',
    email: 'team@cornerstonedev.io',
    vip_score: 47,
    vip_tier: 'Medium',
    step: 4,
    status: 'completed',
    created_at: '2026-03-18T10:00:00Z',
    next_send_at: null,
  },
  {
    id: 106,
    company_name: 'Vantage Capital',
    email: 'info@vantagecap.com',
    vip_score: 38,
    vip_tier: 'Low',
    step: 2,
    status: 'lost',
    created_at: '2026-03-15T12:00:00Z',
    next_send_at: null,
  },
];

export const MOCK_METRICS = {
  leads_today: 14,
  avg_score: 67,
  sequences_active: 8,
  emails_sent: 312,
};

export const MOCK_AGENTS = [
  {
    id: 'pipeline',
    name: 'Pipeline Agent',
    status: 'idle',
    stat: '14 leads enriched today',
    last_run: '2026-03-25T09:48:00Z',
  },
  {
    id: 'sequence',
    name: 'Sequence Agent',
    status: 'running',
    stat: '3 sequences queued',
    last_run: '2026-03-25T10:02:00Z',
  },
  {
    id: 'scout',
    name: 'Scout Agent',
    status: 'idle',
    stat: '87 companies scouted this week',
    last_run: '2026-03-25T08:30:00Z',
  },
  {
    id: 'scorer',
    name: 'Scorer Agent',
    status: 'idle',
    stat: 'Avg score 67 · 6 VIPs found',
    last_run: '2026-03-25T09:50:00Z',
  },
  {
    id: 'prospect',
    name: 'Prospect Agent',
    status: 'idle',
    stat: '41 prospects added this week',
    last_run: '2026-03-25T07:15:00Z',
  },
  {
    id: 'chat',
    name: 'Chat Agent',
    status: 'standby',
    stat: 'V1 — always standby',
    last_run: null,
  },
];

export const MOCK_FEED = [
  { timestamp: '2026-03-25T10:02:00Z', agent: 'Sequence Agent', action: 'Sent step 2 email → cto@apexlogistics.io' },
  { timestamp: '2026-03-25T09:58:00Z', agent: 'Scorer Agent', action: 'Scored founders@novaspark.ai → 84 (VIP)' },
  { timestamp: '2026-03-25T09:50:00Z', agent: 'Pipeline Agent', action: 'Enriched hello@brightfieldstudio.co via Apollo' },
  { timestamp: '2026-03-25T09:45:00Z', agent: 'Scout Agent', action: 'Found 6 new companies matching ICP filters' },
  { timestamp: '2026-03-25T09:32:00Z', agent: 'Sequence Agent', action: 'Queued step 3 email → operations@meridianhealth.com' },
  { timestamp: '2026-03-25T09:15:00Z', agent: 'Scorer Agent', action: 'Scored operations@meridianhealth.com → 73 (High)' },
  { timestamp: '2026-03-25T08:55:00Z', agent: 'Pipeline Agent', action: 'Enriched cto@apexlogistics.io — 2 trigger events found' },
  { timestamp: '2026-03-25T08:30:00Z', agent: 'Scout Agent', action: 'Scouted 12 companies in Logistics + AI verticals' },
  { timestamp: '2026-03-25T08:14:00Z', agent: 'Prospect Agent', action: 'Added Apex Logistics to pipeline from Apollo list' },
  { timestamp: '2026-03-25T07:58:00Z', agent: 'Sequence Agent', action: 'Marked NovaSpark AI as replied — paused sequence' },
];
